-keep class by.anegin.telegram_contests.core.ui.view.ChartView$OnUiChartChangeListener
-keep class by.anegin.telegram_contests.core.ui.view.ChartView$OnRangeChangeListener
-keep class by.anegin.telegram_contests.core.ui.view.ChartView$OnGraphVisibilityChangeListener
